---
latitude: 55.75791
longitude: 37.60432
map_zoom: 12
name: Courtyard by Marriott Moscow City Center
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: Voznesenskiy Pereulok 7
  street2: ''
  state: ''
  city: Moscow
  country: 
  zip_code: '125009'
_hotel_id: COU638
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt/.
